apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: vpn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: vpn
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["tailscale-state"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: vpn
subjects:
  - kind: ServiceAccount
    name: tailscale
    namespace: vpn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale
