---
- name: Common Task
  hosts: "{{ env | default('all') }}"
  become: yes
  gather_facts: yes
  become_user: root
  tasks:
    - import_tasks: ../modules/common/main.yml
    - import_tasks: ../modules/patching/main.yml
