---
- hosts: "{{ env }}"
  become: yes
  become_user: root
  vars_files:
    - ../vars/users.yml
  strategy: free
    
  tasks: 
   - include: ../modules/core/sudo/main.yml
   - include: ../modules/core/users/main.yml
