---
- name: Install and Configure Grafana Alloy on Linux Servers
  hosts: all
  become: true
  vars:
    # Envoy Gateway LoadBalancer IP
    gateway_ip: "192.168.122.200"
    # URL of Loki's push API exposed on the Envoy Gateway
    loki_push_url: "http://loki.vennpham.local/loki/api/v1/push"
    # URL of Prometheus remote write API exposed on the Envoy Gateway
    prometheus_remote_write_url: "http://prometheus.vennpham.local/api/v1/write"

  tasks:
    - import_tasks: ../modules/alloy/main.yml
