apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repo_url: https://github.com/venndev20999/homelabs-infrastructure.git
    target_revision: ft/dev
    path: k8s/apps/dev/sample-app # Point this to where your app manifests live
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
