version: '3.8'

services:
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      # This environment variable enables adding/removing clusters at runtime via the UI
      DYNAMIC_CONFIG_ENABLED: 'true'
      # Static cluster configuration for the provided Kafka nodes
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.122.205:9092,192.168.122.206:9092,192.168.122.207:9092
