#ENC[AES256_GCM,data:jNu3UrVVdhVXit2UiHBIzEGmUDnT3JecmvmQotNhrEW5gz6CPhMBBtAkQqMvBDpKyYI16fdxRMLCO+yZVq0I,iv:NWCQN/KR2OIryde3nGNPHprMcTe/X26mPBhDtULyGbk=,tag:fFUzHUGRV8XY4Q8wT4CLpg==,type:comment]
#ENC[AES256_GCM,data:NqnZdD2dOzgDSUecj6xkSVrI4LmvowuUfAmYTYrXPJgVOo8JI8+6JKKBI3eoVA9jOepkAkZV22/6Gb8lm9UJVQ==,iv:Xa63cmwu577rqmBSzpcOfhCWThG7wv6+GR7pINVy5hc=,tag:OUdOPLSVH24uz8NDLqHLOg==,type:comment]
TF_VAR_tailscale_auth_key: ENC[AES256_GCM,data:lzROOa7XPtOfitxtr8VVRf612gr6cPwhgL84E4SHOnT7eHpL9J10Y2HBK7rR4oYlFMzeu6zQ0+7VTAaiDg==,iv:f5PCpoRDilzcFW3dJg96um+Yi90HOBeLsuguFwE1/Ac=,tag:qroovLm2FZY3vA4wvOgMFg==,type:str]
TF_VAR_github_client_id: ENC[AES256_GCM,data:xgk0rTCFJpgZu3opfN8mal8Lnw0=,iv:MLrCUu2dpwfoESSH2EPtcNfUWbo9e1x3iE8o46enf+g=,tag:A0/JVgd3PJhx48XGejo1gg==,type:str]
TF_VAR_github_client_secret: ENC[AES256_GCM,data:7D/yAUgQRihMGuv73mR/SQBbf+IncGlu2mfDXd9Ukn4pvN++pe+KNA==,iv:80vYjwoWp0b9M7XvcErfoSyl6hWV6HvjcYe1WQMatJ0=,tag:z71MgRVE59BUYBQApEKArA==,type:str]
TF_VAR_grafana_github_client_id: ENC[AES256_GCM,data:OoASQ4uZJrVdqojx0qvKAibiKwE=,iv:BPlUL3qg6Q3Voh9dTQaRo5acPN6g3BncuLpwYV1SssI=,tag:3K3ozKvHJP4CWGPWBVpROw==,type:str]
TF_VAR_grafana_github_client_secret: ENC[AES256_GCM,data:xU4Ls39Uve4V1C/vLCSBYVCZ8f3dExl3mgrOqNsqyEuA53+rjXKvew==,iv:bnTM6GW4t8DvPjmQV1/2Jkis9m35VVsUt6/kwdFBLps=,tag:n9GjE+NGdHik+fCwbSddPQ==,type:str]
TF_VAR_minio_endpoint: ENC[AES256_GCM,data:7VMPvtHgCLDa+acPtqJmdmfGEz2UK4A1YQ==,iv:yuA/qXlY0WRfJbmRJYm6mesQAamGD+3VtoSPyuXOIXg=,tag:v0tJwW3pNPxt6T+Olj0UPQ==,type:str]
TF_VAR_minio_access_key: ENC[AES256_GCM,data:8LE2Uxh3JDo=,iv:BzafFWrFOoZqM2ZavmemG17v+OSTCJsV3Q3KweCJkeg=,tag:9rokmKS+7PrOxOTZCLvl2A==,type:str]
TF_VAR_minio_secret_key: ENC[AES256_GCM,data:+ThAHeLf1x7skvA=,iv:pLjF72o/V3EyOZQtxG3znQsyiDnL79OLawb+vNZdzOQ=,tag:TK8Fon3HLYz5Y6ijDi0VQw==,type:str]
#ENC[AES256_GCM,data:q2bPvDHebP/Kvb+3wXmCKZBc+nkZOwC8ID3I4M+JAURq7pBVTYpDPspigA9e38zXG7KOHvRz7AWhBwcrW9jYww==,iv:mb5+Fqrk4o86CjhALm7SBBr6/jxJZVIMMl2fKplx80w=,tag:p7uojlWD6qsZehd4hK2Zkw==,type:comment]
TF_VAR_github_token: ENC[AES256_GCM,data:4xmaBKd1UPZiA4cp3V8cqZpwHPKpJkb6bGae203ReXYZETkeFM+GOw==,iv:BhFMfFdLXdZPJuxxh6BYuzbM4j9C1izc2cHgdBdP/D4=,tag:1IXCgUy0oB4/yb7Q2y+WDg==,type:str]
TF_VAR_clickstack_app_password: ENC[AES256_GCM,data:u5Ow4GfyNCHT/6LHYAOtYGJUCwUScEpM7kQ=,iv:AKDjsO8lIIyGSUx5jxjzo9kTfEOzWIP08U/M7W4t1o0=,tag:WQF/gTyt7FM+M+5/7q7n8A==,type:str]
TF_VAR_clickstack_otel_password: ENC[AES256_GCM,data:0PjRS/wxjC9wnH9iss9l3Cbx+K1qxGT9S5H9EA==,iv:1cp7stozQEsWlyevwKgjraDkv+wBzqEcr/Awd/q/i9A=,tag:hG+XjJsQMIG76FKkqnBnNg==,type:str]
TF_VAR_clickstack_hyperdx_api_key: ENC[AES256_GCM,data:KU9oLO/tTwAV0RnA3tleudqLyieHXeMALu5pMGScbteY1oK7,iv:qrODlcqKiu2qWTKulp8UkKQEnHXf4dbyNK6D4h7VMas=,tag:FQjKz1M2oye6SHyDakojNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R2wyK1FFeCtrOVNYdXF6
            MWh0QUhpT25EcHNGQW5scXpINmVNQlV0MVRnCjAyWnpkMTRwSmJqRkhjQ3NPbko4
            TndFaGhHVFlhckZ1N2Q1VDZndnpuMWMKLS0tIEg0ZlZGTmFSWS9TaGpBS05lNUJy
            Wmg0ZnhjNVBDbHNNVEY2SWdRTnhSRGMKa81r3uT8LZ+Y7yCTjKFY4FQvZa3RyYw2
            +tDnbfpFq00DQoNX+CTMxAVA0emLCAxGN7tMhUvHHHcnWMYbKByvMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cd0m76zs820xg53n3cv9erzp2xs05tnv253yvuyku44x7lcsuqvsgcz9ux
    lastmodified: "2026-09-01T05:57:41Z"
    mac: ENC[AES256_GCM,data:hnGeYXo3n0kUBM7ofZBTxRLR0Y3UyMa07bZHzJEB6EWEaPQaoSBJLyrA55HlrEWlkmIBbvio9+0kDsS4b/zmX3Fux0AixhuDj4iQr0arcU1UEqIeRtmFcIWzFISLdo05fQO4t/31LdnupbAcywNoiXS89GQNq9JqBlVAXGdI6X0=,iv:68zaulmqdIXV7c3QQYEYday1mDSBZ88loT+X4c2Iq/s=,tag:pwtHYICrk6zHHQ94SB2rNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
