---
- hosts: "{{ env }}-api"
  become: yes
  become_user: root
  vars_files:
    - ../vars/nginx-passenger/{{ env }}.yml
  vars:
  tasks:
    - include: ../modules/rvm/main.yml
    - include: ../modules/nginx-passenger/main.yml
  handlers:
    - include: ../modules/nginx-passenger/handlers.yml