hyperdx:
    secrets:
        CLICKHOUSE_APP_PASSWORD: ENC[AES256_GCM,data:Yu6bB+A9k/6ECMhuRlL/8s9iguUeXL8fi9Y=,iv:mO7ouhn6yIqjRpysL+m3iF1ebXeMSKI3G7QlLWGjb9k=,tag:/3nxvUYFfNJ3IEEFrRpTKw==,type:str]
        CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:LAcFsrGkKT8kRBQD8lrxYJr4ft14Xt28uOnV7w==,iv:2pxmfuQy0XOAEp8Y1yUS1R5Lfi++57F+suHpXZGr1Tg=,tag:eTqEL8f3OQ9zrjc/0/wG8A==,type:str]
        HYPERDX_API_KEY: ENC[AES256_GCM,data:3oN2pbSO5alaFXbHdUr7Qr5GRhwEVedAVAbQCr9vgb55k7v8,iv:M3aEMam0PEiJOrtasbeFJiL3+nTar1VZ6T8qphNYN0g=,tag:ktomTVcIUzFk5QuhAJl32A==,type:str]
        MONGODB_PASSWORD: ENC[AES256_GCM,data:xloD6aonfXBrRFCpR0H1WU7URvCLH4BO,iv:JUcHhQyjUlWcrN0DSLnfLW7rMmd1/REUleJaJCGrH6o=,tag:8gsg78honFsbH9eI1BYnVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aGxmNjBUM0hSUVdUd3Qx
            WGdZcXNWaXZDK1ZKVjJkVGJYM1I0Zi9vRmcwCnZjYkphMUhuWjlMWjBGS053bDV0
            Q05tOUtPcXVTcWZoaWFqcTdyYXo4SlkKLS0tIHVweEcza1JlQXBJZ29VNG5IWjcv
            SkN1UThiUTY4UVI5dUNublZ5VjlmMGcKbIj51bfwNksaRflMi94Pg0MmgQZ7KMqy
            2RwBtPJM4hbPrh38L8mIDsDPy+ueyn/xiSW8a9uGGfxpOhel98fg1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cd0m76zs820xg53n3cv9erzp2xs05tnv253yvuyku44x7lcsuqvsgcz9ux
    lastmodified: "2026-09-01T10:33:53Z"
    mac: ENC[AES256_GCM,data:QWeyDOOEpK9AzsW7y2ksVbnbb923s31fSe7vBgyTLeAxUsKwMBCZfSyBG8hd/MofSB60S1GJSbN9fACWFoPyvIVoHutSKZQRVqqyHvE4pD3LcQktOY6TjWUsIGb7GGucv4VgJ4rYipdJiRE2f+cdmH5ULhSML0xnUXXfQ8X8cBA=,iv:9qO0mbaX/xkOjuv59BSToPPIkQrvTgvfR/D1dnlDM+E=,tag:9z4349YkERPeCDJ0kOFHVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
