# infrastructure/k8s/argocd/fleet-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-fleet
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: python-test-app
                  repo: https://github.com/venndev20999/python-test-app.git
          - list:
              elements:
                - env: dev
                  cluster_name: in-cluster    # Deploys to the cluster ArgoCD is running on
                # - env: test
                #   cluster_name: test-cluster  # Matches the 'name' in your Terraform secret
                # - env: prod
                #   cluster_name: prod-cluster  # Placeholder for your future prod cluster
  template:
    metadata:
      name: '{{name}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        targetRevision: dev
        path: 'k8s/overlays/{{env}}'
      destination:
        # 🚀 Using 'name' instead of 'server' is best practice for multi-cluster
        name: '{{cluster_name}}'
        namespace: '{{name}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
