# k8s/argocd-apps/apps/clickstack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: clickstack
      repoURL: "https://clickhouse.github.io/ClickStack-helm-charts"
      targetRevision: 3.2.0
      helm:
        valueFiles:
          - "$values/k8s/helm/clickstack/values.yaml"
          - "$values/k8s/helm/clickstack/secrets.enc.yaml"
    - repoURL: "https://github.com/venndev20999/homelabs-infrastructure.git"
      targetRevision: dev
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: clickstack

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
